#############################################################################
# Makefile for building: gmail
# Generated by qmake (2.01a) (Qt 4.8.2) on: Thu Nov 22 21:35:04 2012
# Project:  gmailsniffer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile gmailsniffer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtWebKit -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gmailatom.cpp \
		email.cpp \
		dialogsettings.cpp \
		settings.cpp \
		sniffernotifier.cpp \
		aboutsniffer.cpp \
		simplecrypt.cpp moc_mainwindow.cpp \
		moc_dialogsettings.cpp \
		moc_sniffernotifier.cpp \
		moc_aboutsniffer.cpp \
		qrc_systrey.cpp
OBJECTS       = main.o \
		mainwindow.o \
		gmailatom.o \
		email.o \
		dialogsettings.o \
		settings.o \
		sniffernotifier.o \
		aboutsniffer.o \
		simplecrypt.o \
		moc_mainwindow.o \
		moc_dialogsettings.o \
		moc_sniffernotifier.o \
		moc_aboutsniffer.o \
		qrc_systrey.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		gmailsniffer.pro
QMAKE_TARGET  = gmail
DESTDIR       = 
TARGET        = gmail

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_dialogsettings.h ui_sniffernotifier.h ui_aboutsniffer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gmailsniffer.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile gmailsniffer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile gmailsniffer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/gmail1.0.0 || $(MKDIR) .tmp/gmail1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gmail1.0.0/ && $(COPY_FILE) --parents mainwindow.h gmailatom.h email.h dialogsettings.h settings.h sniffernotifier.h aboutsniffer.h simplecrypt.h .tmp/gmail1.0.0/ && $(COPY_FILE) --parents systrey.qrc .tmp/gmail1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp gmailatom.cpp email.cpp dialogsettings.cpp settings.cpp sniffernotifier.cpp aboutsniffer.cpp simplecrypt.cpp .tmp/gmail1.0.0/ && $(COPY_FILE) --parents mainwindow.ui dialogsettings.ui sniffernotifier.ui aboutsniffer.ui .tmp/gmail1.0.0/ && (cd `dirname .tmp/gmail1.0.0` && $(TAR) gmail1.0.0.tar gmail1.0.0 && $(COMPRESS) gmail1.0.0.tar) && $(MOVE) `dirname .tmp/gmail1.0.0`/gmail1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gmail1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_dialogsettings.cpp moc_sniffernotifier.cpp moc_aboutsniffer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_dialogsettings.cpp moc_sniffernotifier.cpp moc_aboutsniffer.cpp
moc_mainwindow.cpp: gmailatom.h \
		email.h \
		ui_mainwindow.h \
		dialogsettings.h \
		mainwindow.h \
		sniffernotifier.h \
		settings.h \
		aboutsniffer.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_dialogsettings.cpp: mainwindow.h \
		gmailatom.h \
		email.h \
		ui_mainwindow.h \
		dialogsettings.h \
		sniffernotifier.h \
		settings.h \
		aboutsniffer.h \
		dialogsettings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogsettings.h -o moc_dialogsettings.cpp

moc_sniffernotifier.cpp: settings.h \
		sniffernotifier.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sniffernotifier.h -o moc_sniffernotifier.cpp

moc_aboutsniffer.cpp: aboutsniffer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutsniffer.h -o moc_aboutsniffer.cpp

compiler_rcc_make_all: qrc_systrey.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_systrey.cpp
qrc_systrey.cpp: systrey.qrc \
		images/gmailblue.png \
		images/gmailtest.png \
		images/gmailred.png \
		images/gmailredsmall.png \
		images/application-exit.png \
		images/gtk-info.png \
		images/package-downgrade.png \
		images/preferences-system.png \
		images/package-upgrade.png
	/usr/bin/rcc -name systrey systrey.qrc -o qrc_systrey.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialogsettings.h ui_sniffernotifier.h ui_aboutsniffer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialogsettings.h ui_sniffernotifier.h ui_aboutsniffer.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_dialogsettings.h: dialogsettings.ui
	/usr/bin/uic-qt4 dialogsettings.ui -o ui_dialogsettings.h

ui_sniffernotifier.h: sniffernotifier.ui
	/usr/bin/uic-qt4 sniffernotifier.ui -o ui_sniffernotifier.h

ui_aboutsniffer.h: aboutsniffer.ui
	/usr/bin/uic-qt4 aboutsniffer.ui -o ui_aboutsniffer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		gmailatom.h \
		email.h \
		ui_mainwindow.h \
		dialogsettings.h \
		sniffernotifier.h \
		settings.h \
		aboutsniffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gmailatom.h \
		email.h \
		ui_mainwindow.h \
		dialogsettings.h \
		sniffernotifier.h \
		settings.h \
		aboutsniffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

gmailatom.o: gmailatom.cpp gmailatom.h \
		email.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gmailatom.o gmailatom.cpp

email.o: email.cpp email.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o email.o email.cpp

dialogsettings.o: dialogsettings.cpp dialogsettings.h \
		mainwindow.h \
		gmailatom.h \
		email.h \
		ui_mainwindow.h \
		sniffernotifier.h \
		settings.h \
		aboutsniffer.h \
		ui_dialogsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogsettings.o dialogsettings.cpp

settings.o: settings.cpp settings.h \
		simplecrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

sniffernotifier.o: sniffernotifier.cpp sniffernotifier.h \
		settings.h \
		ui_sniffernotifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sniffernotifier.o sniffernotifier.cpp

aboutsniffer.o: aboutsniffer.cpp aboutsniffer.h \
		ui_aboutsniffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutsniffer.o aboutsniffer.cpp

simplecrypt.o: simplecrypt.cpp simplecrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplecrypt.o simplecrypt.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dialogsettings.o: moc_dialogsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogsettings.o moc_dialogsettings.cpp

moc_sniffernotifier.o: moc_sniffernotifier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sniffernotifier.o moc_sniffernotifier.cpp

moc_aboutsniffer.o: moc_aboutsniffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutsniffer.o moc_aboutsniffer.cpp

qrc_systrey.o: qrc_systrey.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_systrey.o qrc_systrey.cpp

####### Install

install:   FORCE
	cp images/gmailsniffer.png /usr/share/icons/gmailsniffer.png &
	cp gmail /usr/bin/gmailsniffer 

uninstall:   FORCE
	rm /usr/bin/gmailsniffer
FORCE:

